//Array con productos disponibles para la venta
const listadoProductos = [ {nombre: "ARENA", value: "arenacarro", precio: 1950, id:0, stock: 10, img:"../imagenes/arena.jpg",} ,
{nombre: "PIEDRA", value: "piedracarro", precio: 4000, id:1, stock: 10000, img:"../imagenes/piedra.jpg",} ,
{nombre: "CEMENTO LOMA NEGRA", value: "lomanegra", precio: 900, id:2, stock: 10000, img:"../imagenes/cementolomanegra.jpg",} ,
{nombre: "CEMENTO AVELLANEDA", value: "avellaneda", precio: 700, id:3,  stock: 10000, img:"../imagenes/cementoavellaneda.jpg",} ,
{nombre: "CEMENTO HOLCIM", value: "holcicom", precio: 650, id:4 , stock: 10000, img:"../imagenes/cementoholcim.jpg",} ,
{nombre: "CEMENTO COMODORO", value: "comodoro", precio: 890, id:5, stock: 10000, img:"../imagenes/cementocomodoro.png",} ,
{nombre: "CAL MALAGUEÑO", value: "malagueño", precio: 800, id:6 , stock: 10000, img:"../imagenes/cal3.jpg",} ,
{nombre: "CAL SANTA ELENA", value: "santaelena", precio: 900, id:7 , stock: 10000, img: "../imagenes/cal1.jpg", } ,
{nombre: "CAL EL MILAGRO",  value: "elmilagro",precio: 970, id:8 , stock: 10000, img: "../imagenes/cal2.jpg",} ,
{nombre: "HIDROFUGO PROTEX", value: "protex", precio: 300, id:9 , stock: 10000, img: "../imagenes/hidrofugoprotex.jpg",} ,
{nombre: "HIDROFUGO SIKA", value: "sikasika", precio: 400, id:10 , stock: 10000, img: "../imagenes/hidrofugosika.jpg", } ,
{nombre: "HIDROFUGO WEBER", value: "weber", precio: 370, id:11 , stock: 10000, img: "../imagenes/hidrofugoweber.jpg",} ,
{nombre: "LADRILLO COMUN", value: "ladrillocomun", precio: 30, id:12 , stock: 10000,img: "../imagenes/ladrillocomun.jpg",} ,
{nombre: "LADRILLON", value: "ladrillon" , precio: 40, id:13 , stock: 10000, img: "../imagenes/ladrillon.jpg",} ,
{nombre: "BLOQUE VIBRADO", value: "bloquevibrado", precio: 55, id:14 , stock: 10000, img: "../imagenes/cementovibrado.jpg",} ,
{nombre: "LADRILLO HUECO 8", value: "ladrillohueco8", precio: 50, id:15 , stock: 10000, img: "../imagenes/hueco8.png",} ,
{nombre: "LADRILLO HUECO 12", value: "ladrillohueco12", precio: 50, id:16 , stock: 10000, img: "../imagenes/hueco12.jpg",} ,
{nombre: "LADRILLO HUECO 18", value: "ladrillohueco18", precio: 50, id:17 , stock: 10000, img: "../imagenes/hueco18.jpg",} ,
{nombre: "PINTURA ASFALTICA MAXHAUS", value: "maxhaus", precio: 780, id:18 , stock: 10000, img: "../imagenes/maxhaus.png",} ,
{nombre: "PINTURA ASFALTICA MEGAFLEX", value: "megaflex", precio: 700, id:19 , stock: 10000, img: "../imagenes/megaflex.jpg",} ,
{nombre: "PINTURA ASFALTICA DESSUTOL", value: "dessutol", precio: 600, id:20 , stock: 10000, img: "../imagenes/dessutol.jpg",} ,
]